packages:
  - apps/*
  - docs-site
  - examples/*
  - packages/*

engineStrict: true
strictPeerDependencies: true
autoInstallPeers: false
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build

allowBuilds:
  esbuild: true
  libxmljs2: true
  protobufjs: true
  tree-sitter: true
