#!/usr/bin/env node
import { randomUUID } from 'node:crypto';
import express from 'express';
import { A2A_PROTOCOL_VERSION, AGENT_CARD_PATH, TaskState } from '@a2a-js/sdk';
import { AgentEvent, DefaultRequestHandler, InMemoryTaskStore } from '@a2a-js/sdk/server';
import { UserBuilder, agentCardHandler, jsonRpcHandler } from '@a2a-js/sdk/server/express';

const port = Number(process.env['A2A_INTEROP_PORT'] ?? '0');

function messageText(message) {
  return message.parts
    .filter((part) => part.content?.$case === 'text')
    .map((part) => part.content.value)
    .join(' ');
}

class LiveJavaScriptExecutor {
  async cancelTask(taskId, eventBus) {
    eventBus.publish(
      AgentEvent.statusUpdate({
        taskId,
        contextId: '',
        status: {
          state: TaskState.TASK_STATE_CANCELED,
          timestamp: new Date().toISOString(),
          message: undefined,
        },
        metadata: {},
      }),
    );
  }

  async execute(requestContext, eventBus) {
    const userMessage = requestContext.userMessage;
    const taskId = requestContext.taskId;
    const contextId = requestContext.contextId;
    const task = requestContext.task ?? {
      id: taskId,
      contextId,
      status: {
        state: TaskState.TASK_STATE_SUBMITTED,
        timestamp: new Date().toISOString(),
        message: undefined,
      },
      artifacts: [],
      history: [userMessage],
      metadata: {},
    };
    eventBus.publish(AgentEvent.task(task));
    eventBus.publish(
      AgentEvent.statusUpdate({
        taskId,
        contextId,
        status: {
          state: TaskState.TASK_STATE_WORKING,
          timestamp: new Date().toISOString(),
          message: undefined,
        },
        metadata: {},
      }),
    );
    await new Promise((resolve) => setTimeout(resolve, 20));
    eventBus.publish(
      AgentEvent.artifactUpdate({
        taskId,
        contextId,
        artifact: {
          artifactId: randomUUID(),
          name: 'Official JavaScript artifact',
          description: 'Generated by @a2a-js/sdk live interop server.',
          parts: [
            {
              content: { $case: 'text', value: `javascript:${messageText(userMessage)}` },
              metadata: undefined,
              filename: '',
              mediaType: 'text/plain',
            },
          ],
          metadata: {},
          extensions: [],
        },
        lastChunk: true,
        append: false,
        metadata: {},
      }),
    );
    eventBus.publish(
      AgentEvent.statusUpdate({
        taskId,
        contextId,
        status: {
          state: TaskState.TASK_STATE_COMPLETED,
          timestamp: new Date().toISOString(),
          message: undefined,
        },
        metadata: {},
      }),
    );
  }
}

const card = {
  name: 'Official JavaScript live server',
  description: 'Loopback-only @a2a-js/sdk live interoperability participant.',
  supportedInterfaces: [
    {
      url: 'http://127.0.0.1:0/a2a/jsonrpc',
      protocolBinding: 'JSONRPC',
      tenant: '',
      protocolVersion: A2A_PROTOCOL_VERSION,
    },
  ],
  provider: {
    organization: 'A2A Mesh interoperability',
    url: 'https://github.com/oaslananka/a2amesh',
  },
  version: '1.0.0',
  capabilities: {
    streaming: true,
    pushNotifications: false,
    extensions: [],
    extendedAgentCard: false,
  },
  securitySchemes: {},
  securityRequirements: [],
  defaultInputModes: ['text/plain'],
  defaultOutputModes: ['text/plain'],
  skills: [
    {
      id: 'live-interop',
      name: 'Live interoperability',
      description: 'Returns a deterministic text artifact.',
      tags: ['interop'],
      examples: ['hello live stream'],
      inputModes: ['text/plain'],
      outputModes: ['text/plain'],
      securityRequirements: [],
    },
  ],
  documentationUrl: '',
  signatures: [],
};

const requestHandler = new DefaultRequestHandler(
  card,
  new InMemoryTaskStore(),
  new LiveJavaScriptExecutor(),
);
const app = express();
app.use(`/${AGENT_CARD_PATH}`, agentCardHandler({ agentCardProvider: requestHandler }));
app.use(
  '/a2a/jsonrpc',
  jsonRpcHandler({ requestHandler, userBuilder: UserBuilder.noAuthentication }),
);

const listener = app.listen(port, '127.0.0.1', () => {
  const address = listener.address();
  if (!address || typeof address === 'string') {
    console.error('Unable to resolve official JavaScript server port');
    process.exit(1);
  }
  const url = `http://127.0.0.1:${address.port}`;
  card.supportedInterfaces[0].url = `${url}/a2a/jsonrpc`;
  process.stdout.write(
    `${JSON.stringify({
      type: 'ready',
      participant: 'official-javascript-server',
      sdk: '@a2a-js/sdk',
      sdkVersion: '1.0.0',
      protocolVersion: A2A_PROTOCOL_VERSION,
      url,
    })}\n`,
  );
});

listener.once('error', (error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});

function shutdown() {
  listener.close(() => process.exit(0));
}
process.once('SIGTERM', shutdown);
process.once('SIGINT', shutdown);
