{{- if .Values.serviceAccount.create }}
{{- if .Values.registry.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "a2amesh.registryServiceAccountName" . }}
  labels:
    {{- include "a2amesh.componentLabels" (dict "root" . "component" "registry") | nindent 4 }}
  {{- with (mergeOverwrite (dict) .Values.commonAnnotations .Values.serviceAccount.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
---
{{- end }}
{{- if .Values.runtime.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "a2amesh.runtimeServiceAccountName" . }}
  labels:
    {{- include "a2amesh.componentLabels" (dict "root" . "component" "runtime") | nindent 4 }}
  {{- with (mergeOverwrite (dict) .Values.commonAnnotations .Values.serviceAccount.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
